# Disable the "core" node plugins
disablePlugins:
  - lando-node

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/node": /home/runner/work/node/node

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev
