name: lando-node-18
services:
  defaults:
    type: node:18
    build:
      - yarn
    command: /app/node_modules/.bin/nodemon src/app-http.js --watch src --ignore *.test.js
  cli:
    type: node
  compass:
    type: node:18
    globals:
      grunt-cli: latest
    build_as_root:
      - apt-get update -y
      - apt-get install ruby-full -y
      - gem install compass
  custom:
    type: node:17
    ssl: true
    globals:
      gulp-cli: latest
    port: 3000
    build:
      - yarn
    command: /app/node_modules/.bin/nodemon src/app-https.js --watch src --ignore *.test.js
  custom2:
    type: node:18.13.0
    ssl: 4444
    port: 3000
    build:
      - yarn
    command: /app/node_modules/.bin/nodemon src/app-custom.js --watch src --ignore *.test.js
  patch:
    type: node:18.12.1
tooling:
  ruby:
    service: compass
  compass:
    service: compass

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/node": ./../../
