name: Node Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        leia-test:
          - examples/10
          - examples/12
          - examples/14
          - examples/16
          - examples/18
          - examples/19
        lando-version:
          - 3-dev
        os:
          - ubuntu-22.04
        node-version:
          - '16'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            plugins.@lando/node=/home/runner/work/node/node
          telemetry: false
      - name: Verify Lando works and we are dogfooding this plugin for tests
        run: |
          lando version
          lando config --path plugins | grep node | grep /home/runner/work/node/node || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
